on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to publish'
        required: true
      package_path:
        description: 'Path to .nupkg file (default .nupkgs/*.nupkg)'
        default: '.nupkgs/*.nupkg'
        required: false

jobs:
  publish-nuget-org:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore --configfile nuget.config

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Pack NuGet package
        run: dotnet pack ./AspectLib/AspectLib.csproj --no-build --configuration Release --output .nupkgs --version ${{ github.event.inputs.version }}

      - name: Publish package to NuGet.org
        run: dotnet nuget push ${{ github.event.inputs.package_path }} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate